name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_wheels_macos:
    name: Build wheels on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: 'v0.2.20'
          submodules: 'recursive'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS_MACOS: x86_64 universal2
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"
          CIBW_BEFORE_BUILD: "pip install build wheel cmake"
      - name: List wheels
        run: ls -la /wheelhouse/*.whl
