name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build linux/arm64 wheels
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout abetlen/llama-cpp-python"
        uses: actions/checkout@v4
        with:
          repository: 'abetlen/llama-cpp-python'
          ref: 'v0.2.20'
          submodules: 'recursive'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_SKIP: "*musllinux* pp*"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_ARCHS: "aarch64"
          CIBW_BUILD: "cp311-*"
        with:
          output-dir: public/llama_cpp_python/

      - name: List wheelhouse contents
        run: ls -la public/llama_cpp_python/

      - name: Make Python Package Index
        uses: girder/create-pip-index-action@main
        with:
          package_directory: public/llama_cpp_python/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}